### ISSUE TITLE
Ionic cloud packaging failed because can't install cordova-plugin-braintree

### ISSUE THREAD

**Issue by SerhiiZiatko** [Taracque/cordova-plugin-braintree#29]
Hi, could you help me, I'm trying to use ionic cloud packaging for my project and I get error when I run ionic package build ios
...
Failed to install 'cordova-plugin-braintree':Error: Cannot find module 'xcode'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.require (module.js:483:17)
at require (internal/module.js:20:19)
at Object. (/Users/package/workspace/apps-6de78f93-2/cordova/plugins/cordova-plugin-braintree/scripts/add_embedded_ios_frameworks.js:3:15)
at Module._compile (module.js:556:32)
at Object.Module._extensions..js (module.js:565:10)
at Module.load (module.js:473:32)__emphasized text
at tryModuleLoad (module.js:432:12)
at Function.Module._load (module.js:424:3)
Failed to restore plugin "cordova-plugin-braintree" from config.xml. You might need to try adding it again. Error: Error: Cannot find module 'xcode'
Error: Cannot find module 'xcode'

How can I solve this issue? thanks:)

**Comment by Taracque** [comment]
This means, that XCode npm module is missing. I  don't know how Ionic Package works, as I see, they are not supporting custom hooks (https://docs.ionic.io/services/package/#hooks). You should ask Ionic Cloud support about that. I'd be happy if you could post a followup on this.
